site_name: TechZone Accelerator Toolkit
site_description: >-
  Exploration of TechZone Accelerator Toolkit
site_url: https://binnes.github.io/TechZoneAutomation/
site_author: Brian Innes
repo_name: "TechZoneAutomation"
repo_url: https://github.com/binnes/TechZoneAutomation
docs_dir: docs
site_dir: public
edit_uri: edit/main/docs
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - navigation.instant
    - naviagation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - search.suggest
    - search.highlight
use_directory_urls: true
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
nav:
  - Home: index.md
  - Plan: plan.md
  - Setup: setup.md
  - Bill of Materials: bom.md
  - Deploy: deploy.md
  - Helm: helm.md
  - Reference:  reference.md
  - Learning Env: learningEnvironment.md
  - Create/Update Module: module.md
